#Python Base Image
FROM python:3.9

#Setting /app as working directory
WORKDIR /app

#Copying requirements.txt and install dependencies
COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY main.py templates/ /app

# Expose the port that Flask app is running on
EXPOSE 5000

# Set the environment variable to run the Flask app
ENV FLASK_APP=main.py

# Command to run the Flask app when the container starts
CMD ["flask", "run", "--host=0.0.0.0"]





